<?php

namespace BES\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends \SKCMS\CoreBundle\Repository\SKEntityRepository
{
}
