<?php

namespace SKCMS\CoreBundle\Entity;

use SKCMS\CoreBundle\Repository\SKEntityRepository;

/**
 * ContactInfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactInfosRepository extends SKEntityRepository
{
}
