<?php

namespace SKCMS\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntityListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityListRepository extends EntityRepository
{
}
