<?php

namespace SKCMS\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use SKCMS\CoreBundle\Repository\SKEntityRepository;

/**
 * MenuElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuElementRepository extends SKEntityRepository
{
    public function findRootMenu($locale = null)
    {
        $qb = $this->createQueryBuilder('m')
                ->leftJoin('m.children','c')
                ->leftJoin('c.children','cc')
                ->leftJoin('cc.children','ccc')
                ->addSelect('cc')
                ->addSelect('c')
                ->addSelect('ccc')
                ->where('m.parent IS null')
                ;
        
        return $this->getResult($qb,$locale);
        
                
    }
    
    public function findMenu($id)
    {
        $qb = $this->createQueryBuilder('m')
                ->where('m.id = :id')
                ->setParameter('id', $id)
                ->leftJoin('m.children','c')
                ->leftJoin('c.children','cc')
                ->leftJoin('cc.children','ccc')
                ->addSelect('cc')
                ->addSelect('c')
                ->addSelect('ccc')
                ;
        return $this->getOneOrNullResult($qb);

    }
    
}
