<?php

namespace SKCMS\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SKBasePageRepository extends \SKCMS\CoreBundle\Repository\SKEntityRepository
{
    
    public function findForAdmin($id,$locale = null)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.id=:id')
                ->setParameter('id', $id)
            ->leftJoin('p.template', 't')
                ->addSelect('t')
            ;
        
        return $this->getOneOrNullResult($qb,$locale);
    }
    
}
