<?php

namespace SKCMS\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SKImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SKImageRepository extends EntityRepository
{
}
