<?php

namespace SKCMS\TrackingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
    
    public function findLast6Months()
    {
        $from = new \DateTime();
        $from->modify('-6 month');
        
        $qb = $this->createQueryBuilder('s');
        
        $qb->where('s.date>:from')
            ->setParameter('from', $from);
        
        return $qb->getQuery()->getResult();
    }
    
    public function countByMonth(\DateTime $receivedDate)
    {
        $dateStart = new \DateTime();
        $dateStart->setDate($receivedDate->format('Y'), $receivedDate->format('n'), 1);
        $dateEnd = new \DateTime();
        $dateEnd->setDate($receivedDate->format('Y'), $receivedDate->format('n'), 1);
        $dateEnd->modify('+1 month');
        
//        //dump($dateStart);
//        //dump($dateEnd);
//        die();
        $qb = $this->createQueryBuilder('s');
        
        $qb ->select('COUNT (s.id)')
            ->where($qb->expr()->between('s.date', ':dateStart', ':dateEnd'))
            ->setParameter('dateStart', $dateStart, \Doctrine\DBAL\Types\Type::DATETIME)
            ->setParameter('dateEnd', $dateEnd, \Doctrine\DBAL\Types\Type::DATETIME)
                
                ;
        
        return $qb->getQuery()->getSingleScalarResult();
    }
    
    
}
