<?php

namespace SKCMS\TrackingBundle\Entity;

use Doctrine\ORM\EntityRepository;
use SKCMS\UserBundle\Entity\User;
/**
 * PostViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewRepository extends EntityRepository
{
    
    public function findGrouppedByDay(\DateTime $limit)
    {
        $qb = $this->createQueryBuilder('v');
        $qb->select('count(v.id) as vCount')
        ->addSelect('v.datein as vDate')
        ->addSelect('SUBSTRING(v.datein, 9, 2) as vDay')
        ->where('v.datein>:date')
        ->setParameter('date', $limit, \Doctrine\DBAL\Types\Type::DATETIME)
        ->groupBy('vDay')
        ->orderBy('v.datein', 'ASC')
                ;
        
        return $qb->getQuery()->getResult();
        
    }
    
    
    public function findViewedPostsId(User $user)
    {
//        $em = $this->getEntityManager();
//        $qb = $em->createQueryBuilder();
//        $qb->select('count(p.id)');
//        $qb ->from('P4MCoreBundle:Post','p')
//        
//        $qb = $catrep ->createQueryBuilder('cc')
//                            ->select('DISTINCT cc.contenttype')
//                            ->Where('cc.contenttype = :type')
//                            ->setParameter('type', 'blogarticle')
//                            ->getQuery();
//
//        $categories = $category->getResult();
//        
//        
//        $qb = $this ->createQueryBuilder('pv')
//                    ->select('DISTINCT pv.post')
//                    ->;
//        
//        $qb->where($qb)
        
        
    }
    
    public function findLastMonthPostReadNumberByUser($user)
    {
        $lastMonth = new \DateTime();
        $lastMonth->modify('-1 month');
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('count(DISTINCT p.post)');
        $qb->from('P4MTrackingBundle:PostView','p');
        $qb ->where('p.user = :user')
            ->setParameter('user', $user)
            ->andWhere('p.datein>:lastMonth')
            ->setParameter('lastMonth', $lastMonth );

        
        
        return $qb->getQuery()->getSingleScalarResult();
        
        
    }
    public function findLastMonthPostReadNumber()
    {
        $lastMonth = new \DateTime();
        $lastMonth->modify('-1 month');
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('count(DISTINCT p.id)');
        $qb->from('P4MTrackingBundle:PostView','p');
        $qb ->where('p.datein>:lastMonth')
            ->setParameter('lastMonth', $lastMonth );

        
        return $qb->getQuery()->getSingleScalarResult();
        
        
    }
}
