
bes_contact:
    resource: "@BESContactBundle/Resources/config/routing.yml"
    prefix:   /

bes_core:
    resource: "@BESCoreBundle/Resources/config/routing.yml"
    prefix:   /


skcms_tracking:
    resource: "@SKCMSTrackingBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: 

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    

skcms_front:
    resource: "@SKCMSFrontBundle/Resources/config/routing.yml"
    prefix:   /

skcms_user:
    resource: "@SKCMSUserBundle/Resources/config/routing.yml"
    prefix:   /

skcms_contact:
    resource: "@SKCMSContactBundle/Resources/config/routing-skcmsContact.yml"
    prefix:   /

skcms_core:
    resource: "@SKCMSCoreBundle/Resources/config/routing.yml"
    prefix:   /

skcmsck_finder:
    resource: "@SKCMSCKFinderBundle/Resources/config/routing/routing.yml"
    prefix:   /

skcms_admin:
    resource: "@SKCMSAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

ck_finder:
    resource: "@JonlilCKFinderBundle/Resources/config/routing/routing.yml"
    prefix: /ckfinder

