parameters:
#    skcms_user.example.class: SKCMS\UserBundle\Example

services:
#    skcms_user.example:
#        class: %skcms_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
